version: '3.8'

services:
  backend:
    image: 2.10-be
    container_name: part2-4-backend
    environment:
      - REQUEST_ORIGIN=http://localhost
      - REDIS_HOST=part2-4-redis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_HOST=part2-6-postgres
    ports:
      - 8080:8080
  frontend:
    image: 2.10-fe
    container_name: part2-4-frontend
    ports:
      - 5000:5000
  redis:
    image: redis
    container_name: part2-4-redis
    ports:
      - 6379:6379
  postgres:
    image: postgres:13.2-alpine
    restart: unless-stopped
    container_name: part2-6-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes: 
      - ./database:/var/lib/postgresql/data
  proxy:
    image: nginx:1.23.2-alpine
    restart: unless-stopped
    container_name: part2-8-proxy
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      