version: '3.8'

services:
  frontend:
    build: ./ml-kurkkumopo-frontend
    container_name: app-frontend
    ports:
      - 3000:3000
  training:
    build: ./ml-kurkkumopo-training
    container_name: app-training
    volumes:
      - model:/src/model
      - imgs:/src/imgs
  backend:
    build: ./ml-kurkkumopo-backend
    container_name: app-backend
    ports:
      - 5000:5000
    volumes:
      - model:/src/model
    

volumes:
  imgs:
  model: